### ISSUE TITLE
Summars-pays table missing 'description'

### ISSUE THREAD

**Issue by overcoin** [daywalker90/summars#12]
This is not an issue. Just trying to make life easier for our accounting department.

Summars-pay has date, time, payment_hash, sats_sent, and destination. Is there any special consideration why 'description' is missing from the summars-pays table?

**Comment by daywalker90** [comment]
I want to keep row length as short as possible for columns that can't be omitted by the user. I also want to be able to call the corresponding `list*` command to get more details about something, e.g. `listpays <payment_hash>`. So for pay we need the full `payment_hash`. This makes the row already pretty long. I think the only way to make everyone happy is yet another config option for each flow table to customize the columns and set max length for descriptions?

**Comment by daywalker90** [comment]
I did some research and it's actually worse for the `description`. Since `listpays` only returns the `description` if it was provided to `pay`. And usually that only happens for very long descriptions where you provide a description hash. So in order for `summars` to display the `description` i have to either make an extra rpc call per payment or import a crate to decode the string. Either way it could increase the response time of summars noticeably for large amounts of payments.

**Comment by overcoin** [comment]
Indeed, max allowed length for the description field is 640 bytes (5*1024 bits) and that is 640 characters which is pretty long for a cli tool. At this stage there is no need to complicate config options with customization of columns max length. For the row length for columns that can be omitted or arbitrarily defined by the user same restriction can be applied. It is already done with the max length of node alias field i.e. beyond certain length extra characters are trimmed and [...] is concatenated. Extra rpc call can not be avoided if we want extra piece of data.

**Comment by daywalker90** [comment]
Fixed in v3.3.0
