### ISSUE TITLE
Feature request: GRAPH_SATS limit indicators

### ISSUE THREAD

**Issue by tsjk** [daywalker90/summars#3]
Thanks for an awesome plugin.
I really like the GRAPH_SATS addition, and now I'm only really missing the limit indicators. The original summary plugin has indicators that show how many sats the extreme values actually amount. Like:
```
├0.1252btc    OUT/OURS ┼ IN/THEIRS   0.1252btc┤
```
Having something similar in summars would be great.

(I can likely do a PR here eventually, but thought I could start with opening an issue)

**Comment by daywalker90** [comment]
fyi: The algorithm that draws the graph is the same as in summary and the limits are always equal. This makes alot of sense in my view since otherwise you would have different scales for "in" and "out". 

I would just modify the column name "GRAP_SATS" to show these limits. Even if these are always equal it makes sense to show them both on each side, since otherwise one value could be confused for the total amount of both sides together.

**Comment by daywalker90** [comment]
fixed in #4
